# Generated by Django 4.0 on 2022-01-02 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
