# Generated by Django 4.0 on 2022-01-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_notes_created_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
