# Generated by Django 4.0 on 2022-01-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_rename_courses_course_rename_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='abstract',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='notebook',
            name='foreword',
            field=models.TextField(blank=True),
        ),
    ]
