# Generated by Django 4.0 on 2022-01-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_notebook_abstract_notebook_foreword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='abstract',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
